language: python
cache:
  directories:
  - "$TRAVIS_BUILD_DIR/.eggs"
python:
- '2.7'
- '3.6'
- 3.7-dev
install: 
script: make test
deploy:
  provider: pypi
  user: datashaman
  password:
    secure: WIf1u1SjjfjN9DV42ocLnc1ByZZfDA5NZpxT9JWGWU0H8SjSAA7holjohTyXf73nFYuyQhGeGEcMm2pE9x2mFsV5bxho67pOs8PZtTjBt9iaC8fvu6SgK9bJLkE73+O/PvKigKFAdkKe3CTFzU3ZYEBDjPVEkioATTgmGqeYdGZ7+IhOwEWT40/yVKLeWfc+9/XCc+JHwv/FARDb+zjd4w0FDneYQBdqP+ftr81qeY5xLLB+W3iKhWZmL+22MiBz0oXM5OZ6+ZucMi/oPBEiVc/+W5W39Ou9kCl599J7gENEcSUQthQjxcNicJ0V03YDvmXzweb4OLdTb8e1JaAktLFoXorgtJwRO1K/X3PDPM/iRTSgIjrh36jeO/F9mtTJYLj2lLWXZN3JiTDgYNSBbBOXNiTWGDEdXJoIJNQ1eSrTQ7ziEDOJR2mawJiXb2RgPDAR3NlrfmG6QTVgcDdrtbEDnhfi8cMfXjGkmxyy5LIGNy4jv2z4l7C/J9UtYHgVFhhcvCyKQ06Q7iNOWGeOKdzFys37c6BagMjow4ow9a27Y2rl4Zb2GjxlWLSWsJmGhYNrd0CvuE2HjNC+3qAuyJ729VoASLxDBjAJjm1spaYQE+yV9T1HVOjGAWHVeFzoG61N0CgR9pukB2AYe7WRjb8JBY1NlHDcJpItKZ+jhuM=
